/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paket_C;
import Paket_C.Daftar;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.PreparedStatement;
/**
 *
 * @author WINDOWS
 */
public class Daftar extends javax.swing.JFrame {

    /**
     * Creates new form Daftar
     */
    public Daftar() {
        initComponents();
        id12.setEnabled(false);
        autonumber();
    }
    
    private void autonumber(){
        try{
            Connection c = koneksi_login.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM login ORDER BY id DESC";
            ResultSet r = s.executeQuery(sql);
            if (r.next()){
                String NoID = r.getString("id").substring(2);
                String ID = "" + (Integer.parseInt(NoID) + 1);
                String Zero = "";
                
                if (ID.length()==1)
                {Zero = "00";}
                else if(ID.length()==2)
                {Zero = "0";}
                else if(ID.length()==3)
                {Zero = "";}
                
                id12.setText("ID" + Zero + ID);
            }else{
                id12.setText("001");
            }
            r.close();
            s.close();
        }catch(SQLException e){
            System.out.println("autonumber error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username12 = new javax.swing.JTextField();
        pass12 = new javax.swing.JPasswordField();
        daftar12 = new javax.swing.JButton();
        exit12 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        id12 = new javax.swing.JTextField();
        confirm12 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("DAFTAR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        username12.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(username12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 120, -1));

        pass12.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(pass12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 120, -1));

        daftar12.setBackground(new java.awt.Color(0, 0, 255));
        daftar12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        daftar12.setText("DAFTAR");
        daftar12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftar12ActionPerformed(evt);
            }
        });
        getContentPane().add(daftar12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        exit12.setBackground(new java.awt.Color(0, 0, 255));
        exit12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exit12.setText("EXIT");
        exit12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit12ActionPerformed(evt);
            }
        });
        getContentPane().add(exit12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Id");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 48, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Confirm Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 164, -1, -1));
        getContentPane().add(id12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 45, 120, -1));
        getContentPane().add(confirm12, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 161, 119, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit12ActionPerformed
        this.dispose();
        Login a = new Login();
        a.setVisible(true);
    }//GEN-LAST:event_exit12ActionPerformed

    private void daftar12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftar12ActionPerformed
        dftr df = new dftr();
        df.id = id12.getText();
        df.username = username12.getText();
        df.password = pass12.getText();

        
        try{
            df.simpan();
            JOptionPane.showMessageDialog(null, "Berhasil Membuat akun");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
            this.dispose();
            Login a = new Login();
            a.setVisible(true);
        }
    }//GEN-LAST:event_daftar12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirm12;
    private javax.swing.JButton daftar12;
    private javax.swing.JButton exit12;
    private javax.swing.JTextField id12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pass12;
    private javax.swing.JTextField username12;
    // End of variables declaration//GEN-END:variables
}
