/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paket_C;
import Simpan_Nilai.Simpan;
import javax.swing.JOptionPane;
/**
 *
 * @author WINDOWS
 */
public class Entry_Data_Nilai_Mahasiswa extends javax.swing.JFrame {
    int NMID, NUAS, total, kelas;
    String huruf;

    /**
     * Creates new form Entry_Data_Nilai_Mahasiswa
     */
    public Entry_Data_Nilai_Mahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nim12 = new javax.swing.JTextField();
        nama12 = new javax.swing.JTextField();
        NUmid12 = new javax.swing.JTextField();
        NUakh12 = new javax.swing.JTextField();
        totaln12 = new javax.swing.JTextField();
        kelas12 = new javax.swing.JComboBox<>();
        nh12 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        simpan12 = new javax.swing.JButton();
        proses12 = new javax.swing.JButton();
        ulang12 = new javax.swing.JButton();
        exit12 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Entry Data Nilai Mahasiswa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel2.setText("NIM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 46, -1, -1));

        jLabel3.setText("Nama Mahasiswa");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 74, -1, -1));

        jLabel4.setText("Kelas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 108, -1, -1));

        jLabel5.setText("Nilai Ujian Mid");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 139, -1, -1));

        jLabel6.setText("Nilai Ujian Akhir");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
        getContentPane().add(nim12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 43, 175, -1));
        getContentPane().add(nama12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 74, 175, -1));
        getContentPane().add(NUmid12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 136, 175, -1));
        getContentPane().add(NUakh12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 167, 175, -1));
        getContentPane().add(totaln12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 281, 175, -1));

        kelas12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Informatika-20", "Informatika-21", "Informatika-22", "Teknik Mesin-20", "Teknik Mesin-21", "Teknik Mesin-22", "Teknik Otomotif-20", "Teknik Otomotif-21", "Teknik Otomotif-22" }));
        getContentPane().add(kelas12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 105, 175, -1));
        getContentPane().add(nh12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 312, 175, -1));

        jLabel7.setText("Total Nilai");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 284, -1, -1));

        jLabel9.setText("Nilai Huruf");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 315, -1, -1));

        simpan12.setBackground(new java.awt.Color(255, 255, 0));
        simpan12.setText("Simpan");
        simpan12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan12ActionPerformed(evt);
            }
        });
        getContentPane().add(simpan12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 217, 75, -1));

        proses12.setBackground(new java.awt.Color(255, 255, 0));
        proses12.setText("Proses");
        proses12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proses12ActionPerformed(evt);
            }
        });
        getContentPane().add(proses12, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 217, 77, -1));

        ulang12.setBackground(new java.awt.Color(255, 255, 0));
        ulang12.setText("Ulangi");
        ulang12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulang12ActionPerformed(evt);
            }
        });
        getContentPane().add(ulang12, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 217, 75, -1));

        exit12.setBackground(new java.awt.Color(255, 255, 0));
        exit12.setText("Exit");
        exit12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit12ActionPerformed(evt);
            }
        });
        getContentPane().add(exit12, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 217, 58, -1));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proses12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proses12ActionPerformed
//        kelas = Integer.parseInt((String) kelas12.getSelectedItem());
        NMID = Integer.parseInt(NUmid12.getText());
        NUAS = Integer.parseInt(NUakh12.getText());
        total = (int) ((0.3)*NMID + (0.7)*NUAS);
        
        totaln12.setText(""+total+"");
        if (total ==0){
            nh12.setText(" Selamat anda mendapatkan nilai\nE");
        }
        else if((total>=1)&&(total<=40)){
            nh12.setText("C");
        }
        else if((total>=41)&&(total<=50)){
            nh12.setText("C+");
        }
        else if((total>=51)&&(total<=60)){
            nh12.setText("B-");
        }
        else if((total>=61)&&(total<=70)){
            nh12.setText("B");
        }
        else if((total>=71)&&(total<=80)){
            nh12.setText("B+");
        }
        else if((total>=81)&&(total<=85)){
            nh12.setText("A-");
        }
        else if((total>=86)&&(total<=93)){
            nh12.setText("A");
        }
        else if((total>=94)&&(total<=100)){
            nh12.setText("A+");
        }
        else{
            nh12.setText("Nilai Diluar Nalar:)!");
        }
    }//GEN-LAST:event_proses12ActionPerformed

    private void ulang12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulang12ActionPerformed
        nama12.setText(null);
        nim12.setText(null);
        kelas12.setToolTipText(null);
        NUmid12.setText(null);
        NUakh12.setText(null);
        totaln12.setText(null);
        nh12.setText(null);
    }//GEN-LAST:event_ulang12ActionPerformed

    private void exit12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit12ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exit12ActionPerformed

    private void simpan12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan12ActionPerformed
        Simpan smpn = new Simpan();
        smpn.nim = nim12.getText();
        smpn.nama = nama12.getText();
        smpn.kelas = kelas12.getSelectedItem();
        smpn.nilaimid = NUmid12.getText();
        smpn.nilaiuas = NUakh12.getText();
        smpn.total = totaln12.getText();
        smpn.huruf = nh12.getText();
        
        try{
            smpn.simpan();
            JOptionPane.showMessageDialog(null, "Data dan Nilai berhasil disimpan");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_simpan12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entry_Data_Nilai_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entry_Data_Nilai_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entry_Data_Nilai_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entry_Data_Nilai_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entry_Data_Nilai_Mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NUakh12;
    private javax.swing.JTextField NUmid12;
    private javax.swing.JButton exit12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> kelas12;
    private javax.swing.JTextField nama12;
    private javax.swing.JTextField nh12;
    private javax.swing.JTextField nim12;
    private javax.swing.JButton proses12;
    private javax.swing.JButton simpan12;
    private javax.swing.JTextField totaln12;
    private javax.swing.JButton ulang12;
    // End of variables declaration//GEN-END:variables
}
