/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paket_B;

import Simpan.Simpan;
import javax.swing.JOptionPane;

/**
 *
 * @author WINDOWS
 */
public class Pembayaran_Tagihan_Hotel extends javax.swing.JFrame {
    int harga,kodekamar, lama, bayar;

    /**
     * Creates new form Pembayaran_Tagihan_Hotel
     */
    public Pembayaran_Tagihan_Hotel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nama12 = new javax.swing.JTextField();
        proses12 = new javax.swing.JButton();
        ulangi12 = new javax.swing.JButton();
        exit12 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pembayaran12 = new javax.swing.JTextField();
        lama12 = new javax.swing.JTextField();
        kode12 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ket12 = new javax.swing.JTextArea();
        simpan12 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Pembayaran Tagihan Hotel");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nama Tamu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Kode Kamar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Lama Inap");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));
        getContentPane().add(nama12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 120, -1));

        proses12.setBackground(new java.awt.Color(255, 255, 255));
        proses12.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        proses12.setText("Proses");
        proses12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proses12ActionPerformed(evt);
            }
        });
        getContentPane().add(proses12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        ulangi12.setBackground(new java.awt.Color(255, 255, 255));
        ulangi12.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        ulangi12.setText("Ulangi");
        ulangi12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulangi12ActionPerformed(evt);
            }
        });
        getContentPane().add(ulangi12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 71, -1));

        exit12.setBackground(new java.awt.Color(255, 255, 255));
        exit12.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        exit12.setText("Exit");
        exit12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit12ActionPerformed(evt);
            }
        });
        getContentPane().add(exit12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 70, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Keterangan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Pembayaran");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        pembayaran12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(pembayaran12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 120, -1));
        getContentPane().add(lama12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 120, -1));

        kode12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        getContentPane().add(kode12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 120, -1));

        ket12.setColumns(20);
        ket12.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        ket12.setForeground(new java.awt.Color(0, 0, 204));
        ket12.setRows(5);
        jScrollPane1.setViewportView(ket12);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 240, -1));

        simpan12.setBackground(new java.awt.Color(255, 255, 255));
        simpan12.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        simpan12.setText("Simpan");
        simpan12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan12ActionPerformed(evt);
            }
        });
        getContentPane().add(simpan12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel7.setText("hari");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 114, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ulangi12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulangi12ActionPerformed
        nama12.setText(null);
        kode12.setToolTipText(null);
        lama12.setText(null);
        ket12.setText(null);
        pembayaran12.setText(null);
    }//GEN-LAST:event_ulangi12ActionPerformed

    private void exit12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit12ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exit12ActionPerformed

    private void proses12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proses12ActionPerformed
        lama = Integer.parseInt(lama12.getText());
            kodekamar=Integer.parseInt(kode12.getItemAt(WIDTH));
            
            bayar=(int) ((lama)*250000);

       
            pembayaran12.setText(""+"Rp."+bayar+"");
            if(bayar >0){ket12.setText("atas nama "+nama12.getText()
                    +"\n"+"Lama menginap selama "+lama+" hari"+
                    "\n"+"dengan total pembayaran \nseperti yang tertera");}
            
            else {ket12.setText("");
            }
    }//GEN-LAST:event_proses12ActionPerformed

    private void simpan12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan12ActionPerformed
        Simpan smpn = new Simpan();
        smpn.nama = nama12.getText();
        smpn.kode = kode12.getSelectedItem();
        smpn.lama_inap = lama12.getText();
        smpn.ket = ket12.getText();
        smpn.jumlah_bayar = pembayaran12.getText();
        
        try{
            smpn.simpan();
            JOptionPane.showMessageDialog(null, "berhasil");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_simpan12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran_Tagihan_Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran_Tagihan_Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran_Tagihan_Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran_Tagihan_Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembayaran_Tagihan_Hotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ket12;
    private javax.swing.JComboBox<String> kode12;
    private javax.swing.JTextField lama12;
    private javax.swing.JTextField nama12;
    private javax.swing.JTextField pembayaran12;
    private javax.swing.JButton proses12;
    private javax.swing.JButton simpan12;
    private javax.swing.JButton ulangi12;
    // End of variables declaration//GEN-END:variables
}
